src/BOS.StarterCode/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using BOS.StarterCode.Models.BOSModels;
using Microsoft.AspNetCore.Mvc;

namespace BOS.StarterCode.Controllers
{
    public class NavigationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NavigateToModule(Guid id, string code, bool isDefault)
        {
            //if (isDefault)
            //{
                switch (code)
                {
                    case "MYPFL":
                        return RedirectToAction("Index", "Profile");
                    case "USERS":
                        return RedirectToAction("Index", "Users");
                    case "ROLES":
                        return RedirectToAction("Index", "Roles");
                    case "PRMNS":
                        return RedirectToAction("Index", "Permissions");
                    default:
                        return RedirectToAction("NavigationMenu", "Home", new { selectedModuleId = id});
                }
            //}
            //else
            //{
            //    ViewBag.ModuleSelected = "You've selected a custom module. Implement the logic to display the correct view";
            //    return RedirectToAction("Index", "Home");
            //}
        }
    }
}

src/BOS.StarterCode/Views/Shared/NavigationMenu.cshtml
<ul id="navigation-tree">
    @if (Model.ModuleOperations != null)
    {
        @foreach (var module in Model.ModuleOperations)
        {
            @if (module.ChildModules.Count == 0)
            {
                if (@module.Code != "PRMNS")
                {
                    <li id="@module.Id">
                        <a asp-controller="Navigation" asp-action="NavigateToModule" id="@module.Id" asp-route-id="@module.Id" asp-route-code="@module.Code" asp-route-isdefault="@module.IsDefault" parentmoduleid="@module.ParentModuleId">
                            <i class="fa fa-tachometer-alt"></i>
                            <span>@module.Name</span>
                        </a>
                    </li>
                }
            }
            else
            {
                <li class="sidebar-dropdown" id="@module.Id">
                    <a asp-controller="Navigation" asp-action="NavigateToModule" id="@module.Id" asp-route-id="@module.Id" asp-route-code="@module.Code" asp-route-isdefault="@module.IsDefault" parentmoduleid="@module.ParentModuleId">
                        <i class="far fa-user"></i>
                        <span>@module.Name</span>
                    </a>
                    <div class="sidebar-submenu" id="@module.Id">
                        <ul>
                            @foreach (var subModule in module.ChildModules)
                            {
                                if (subModule.ChildModules.Count == 0)
                                {
                                    <li id="@subModule.Id">
                                        <a asp-controller="Navigation" asp-action="NavigateToModule" id="@subModule.Id" asp-route-id="@subModule.Id" asp-route-code="@subModule.Code" asp-route-isdefault="@subModule.IsDefault" parentmoduleid="@subModule.ParentModuleId">
                                            @subModule.Name
                                        </a>
                                    </li>
                                }
                                else
                                {
                                    <li class="sidebar-dropdown" id="@subModule.Id">
                                        <a asp-controller="Navigation" asp-action="NavigateToModule" id="@subModule.Id" asp-route-id="@subModule.Id" asp-route-code="@subModule.Code" asp-route-isdefault="@subModule.IsDefault" parentmoduleid="@subModule.ParentModuleId">
                                            <i class="far fa-user"></i>
                                            <span>@subModule.Name</span>
                                        </a>
                                        <div class="sidebar-submenu" id="@subModule.Id">
                                            <ul>
                                                @foreach (var subSubModule in subModule.ChildModules)
                                                {
                                                    if (subSubModule.ChildModules.Count == 0)
                                                    {
                                                        <li id="@subSubModule.Id">
                                                            <a asp-controller="Navigation" asp-action="NavigateToModule" id="@subSubModule.Id" asp-route-id="@subSubModule.Id" asp-route-code="@subSubModule.Code" asp-route-isdefault="@subSubModule.IsDefault" parentmoduleid="@subSubModule.ParentModuleId">
                                                                @subSubModule.Name
                                                            </a>
                                                        </li>
                                                    }
                                                    else
                                                    {
                                                        <li class="sidebar-dropdown" id="@subSubModule.Id">
                                                            <a asp-controller="Navigation" asp-action="NavigateToModule" id="@subSubModule.Id" asp-route-id="@subSubModule.Id" asp-route-code="@subSubModule.Code" asp-route-isdefault="@subSubModule.IsDefault" parentmoduleid="@subSubModule.ParentModuleId">
                                                                <i class="far fa-user"></i>
                                                                <span>@subSubModule.Name</span>
                                                            </a>
                                                            <div class="sidebar-submenu" id="@subSubModule.Id">
                                                                <ul>
                                                                    @foreach (var subSubSubModule in subSubModule.ChildModules)
                                                                    {
                                                                        if (subSubSubModule.ChildModules.Count == 0)
                                                                        {
                                                                            <li id="@subSubSubModule.Id">
                                                                                <a asp-controller="Navigation" asp-action="NavigateToModule" id="@subSubSubModule.Id" asp-route-id="@subSubSubModule.Id" asp-route-code="@subSubSubModule.Code" asp-route-isdefault="@subSubSubModule.IsDefault" parentmoduleid="@subSubSubModule.ParentModuleId">
                                                                                    @subSubSubModule.Name
                                                                                </a>
                                                                            </li>
                                                                        }
                                                                        else
                                                                        {
                                                                            <li class="sidebar-dropdown" id="@subSubSubModule.Id">
                                                                                <a asp-controller="Navigation" asp-action="NavigateToModule" id="@subSubSubModule.Id" asp-route-id="@subSubSubModule.Id" asp-route-code="@subSubSubModule.Code" asp-route-isdefault="@subSubSubModule.IsDefault" parentmoduleid="@subSubSubModule.ParentModuleId">
                                                                                    <i class="far fa-user"></i>
                                                                                    <span>@subSubSubModule.Name</span>
                                                                                </a>
                                                                                <div class="sidebar-submenu" id="@subSubSubModule.Id">
                                                                                    <ul>
                                                                                        @foreach (var subSubSubSubModule in subSubSubModule.ChildModules)
                                                                                        {
                                                                                            <li id="@subSubSubSubModule.Id">
                                                                                                <a asp-controller="Navigation" asp-action="NavigateToModule" id="@subSubSubSubModule.Id" asp-route-id="@subSubSubSubModule.Id" asp-route-code="@subSubSubSubModule.Code" asp-route-isdefault="@subSubSubSubModule.IsDefault" parentmoduleid="@subSubSubSubModule.ParentModuleId">
                                                                                                    @subSubSubSubModule.Name
                                                                                                </a>
                                                                                            </li>
                                                                                        }
                                                                                    </ul>
                                                                                </div>
                                                                            </li>
                                                                        }
                                                                    }
                                                                </ul>
                                                            </div>
                                                        </li>
                                                    }
                                                }
                                            </ul>
                                        </div>
                                    </li>
                                }
                            }
                        </ul>
                    </div>
                </li>
            }
        }
    }
</ul>

src/BOS.StarterCode/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BOS.StarterCode</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />

    <!--Custom BOS References-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="../lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../css/vanilla-styles.min.css" rel="stylesheet" />
    <script src="../lib/jquery/dist/jquery.min.js"></script>
    <script src="../lib/popper.js/umd/popper.min.js"></script>
    <script src="../lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="shortcut icon" type="image/png" href="../images/favicon.png" />
    <link href="https://use.fontawesome.com/releases/v5.0.1/css/all.css" rel="stylesheet">
    <!-- End Custom BOS References-->
</head>
<body>
    @{
        var hotJarValue = @Configuration.GetSection("Hotjar").Value;
        var googleAnalyticsValue = @Configuration.GetSection("GoogleAnalytics").Value;
    }
    <div class="page-wrapper BOS-theme toggled">
        <partial name="_CookieConsentPartial" />
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/customscripts/custom.js"></script>
    <script>
        function DisplayDialog(dialogObj) {

            if ($('.alert-success').length && dialogObj.Success == true) {
                $("#display_message1").append('<br/>').append(dialogObj.Message);
            }
            else if ($('.alert-danger').length && dialogObj.Success == false) {
                $("#display_message1").append('<br/>').append(dialogObj.Message);
            }
            else {
                var dialog = '<div id="display_message1" class="alert ' + ((dialogObj.Success == true) ? 'alert-success' : 'alert-danger') + ' alert-dismissible fade show">'
                    + '<strong>' + ((dialogObj.Success == true) ? '' : '') + '</strong>  '
                    + ((dialogObj.Message !== '') ? dialogObj.Message : '')
                    + '<a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>'
                    + '</div>';
                $("body").append($(dialog));
                setTimeout(function () {
                    $("#display_message1").remove();
                }, 8000000);
            }
        };

        var ConfirmationObj = null;
        function DisplayConfirmationDialog(dialogObj) {
            ConfirmationObj = null;
            ConfirmationObj = dialogObj;
            //var dialog = '<div id="display_message1" class="alert  alert-info' + ' alert-dismissible fade show">'
            //    + ((dialogObj.Message !== '') ? dialogObj.Message : '')
            //    + '<a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>'
            //    + '<button class="btn btn-search float-right marginright5 margintop-5" type="button" onclick="OnButtonClickedConfirmCancel(); return false;" style="background: #ec5e6b; color: white;">' + dialogObj.CancelData.Label + '</button>'
            //    + '<button class="btn btn-search float-right marginright5 margintop-5" type="button" onclick="OnButtonClickedConfirmOk(); return false;" style="background: #0c93c2; color: white;">' + dialogObj.OkData.Label + '</button>'
            //    + '</div>';

            var dialog = '<div id="display_message1" class="logout_div"> <div class="row"><div class="col-md-12 text-center mb-3" >'
                + ((dialogObj.Message !== '') ? dialogObj.Message : '') + '</div>'
                + '<div class="col-md-6 text-center"><button class="btn btn-warning" onclick="OnButtonClickedConfirmCancel(); return false;">'
                + dialogObj.CancelData.Label + '</button>'
                + '</div><div class="col-md-6 text-center"><button class="btn btn-primary" onclick="OnButtonClickedConfirmOk(); return false;">'
                + dialogObj.OkData.Label + '</button>'
                + '</div></div></div>';

            $("body").append($(dialog));
        };

        function OnButtonClickedConfirmOk() {
            okObj = ConfirmationObj;
            switch (okObj.CallFrom) {
                case "Logout":
                    TriggerLogout();
                    break;
                case "DeleteUser":
                    TriggerDeleteUser(okObj.OkData.Data);
                    break;
                case "DeleteRole":
                    TriggerDeleteRole(okObj.OkData.Data);
                    break;
            }
            $("#display_message1").remove();
        }

        function OnButtonClickedConfirmCancel() {
            cancelObj = ConfirmationObj;
            switch (cancelObj.CallFrom) {
                case "Logout":
                    break;
            }
            $("#display_message1").remove();
        }
        jQuery(function ($) {

            $(".sidebar-dropdown > a").click(function () {
                $(".sidebar-submenu").slideUp(200);
                if (
                    $(this)
                        .parent()
                        .hasClass("active")
                ) {
                    $(".sidebar-dropdown").removeClass("active");
                    $(this)
                        .parent()
                        .removeClass("active");
                } else {
                    $(".sidebar-dropdown").removeClass("active");
                    $(this)
                        .next(".sidebar-submenu")
                        .slideDown(200);
                    $(this)
                        .parent()
                        .addClass("active");
                }
            });

            $("#close-sidebar").click(function () {
                $(".page-wrapper").removeClass("toggled");
            });
            $("#show-sidebar").click(function () {
                $(".page-wrapper").addClass("toggled");
            });




        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>